name: Test playground

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  playing:
    runs-on: ubuntu-latest
    env:
      DEPLOY_FILE: ./README
      APP: ENCODED_ENV
      PROJECT: black

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    # - name: Create env file from secrets
    #   run: echo "${{ secrets.TEST_PROJ }}" > .env.${{ env.APP }}.${{ env.PROJECT }}

    - name: Decode base64 secret
      id: write_file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: '.env.${{ env.PROJECT }}.staging'
        fileDir: './'
        encodedString: ${{ secrets[env.APP] }}

    # - name: Decode private key
    #   run: echo "FIREBASE_PRIVATE_KEY=\"$(echo ${{ secrets.BASE64_THING }} | base64 -d)"\" >> $GITHUB_ENV

    # - name: 'Replace variables in deployment script'
    #   uses: datamonsters/replace-action@v2
    #   with:
    #     files: READMESED
    #     replacements: $TEST=${{ env.FIREBASE_PRIVATE_KEY }}

    - name: cat env
      run: cat .env.black.staging

    # - name: Encode Nginx Conf
    #   run: |
    #     sed -i "s/\$TEST/${{ secrets.TEST }}/g" READMESED
    #     cat READMESED
    - name: Git Version
      id: semvar
      uses: paulhatch/semantic-version@v4.0.3
      with:
        change_path: app1/
        namespace: app1
        format: "${major}.${minor}.${patch}"

    - name: Git Version
      id: semvar2
      uses: paulhatch/semantic-version@v4.0.3
      with:
        change_path: app2/
        namespace: app2
        format: "${major}.${minor}.${patch}"

    - name: Print version
      run:
        echo ${{ steps.semvar.outputs.version }} ${{ steps.semvar.outputs.version_tag }} ${{ steps.semvar.outputs.changed }}

    - name: Print version 2
      run:
        echo ${{ steps.semvar2.outputs.version }} ${{ steps.semvar2.outputs.version_tag }} ${{ steps.semvar2.outputs.changed }}
