name: Test playground

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_landing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

#     - name: 'Replace variables in deployment script'
#       uses: datamonsters/replace-action@v2
#       with:
#         files: README
#         replacements: $TEST=${{ secrets.TEST }}

#     - name: Encode Nginx Conf
#       run: |
#         sed -i "s/\$TEST/${{ secrets.TEST }}/g" READMESED
#         cat READMESED

    - name: Replace file placeholders
      uses: alexrogalskiy/github-action-tag-replacer@master
      with:
        sourceData: ./replacements.json
    
    - name: print README
      run: cat README
