name: Test playground

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  playing:
    runs-on: ubuntu-latest
    env:
      DEPLOY_FILE: ./README

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

    - name: Decode private key
      run: echo "FIREBASE_PRIVATE_KEY=$(echo ${{ secrets.BASE64_THING }} | base64 -d)" >> $GITHUB_ENV

    - name: 'Replace variables in deployment script'
      uses: datamonsters/replace-action@v2
      with:
        files: READMESED
        replacements: $TEST=${{ env.FIREBASE_PRIVATE_KEY }}

    - name: cat READMESED
      run: cat READMESED

    # - name: Encode Nginx Conf
    #   run: |
    #     sed -i "s/\$TEST/${{ secrets.TEST }}/g" READMESED
    #     cat READMESED
